// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8VSeMYuVhumAT8Nht2ZBFfhHgwx6J6Q',
    appId: '1:140441317934:web:20c2936e592a4e43ef65bf',
    messagingSenderId: '140441317934',
    projectId: 'fir-entegrasyon-383cc',
    authDomain: 'fir-entegrasyon-383cc.firebaseapp.com',
    storageBucket: 'fir-entegrasyon-383cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIKX1qObpSVBifIcYuXiXM8WzHNEsWWQ',
    appId: '1:140441317934:android:8ec4ce531721a62def65bf',
    messagingSenderId: '140441317934',
    projectId: 'fir-entegrasyon-383cc',
    storageBucket: 'fir-entegrasyon-383cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7zdIqlQRLmb5Enq8sGw_dOJorJYV4PE',
    appId: '1:140441317934:ios:e053356bf3785edcef65bf',
    messagingSenderId: '140441317934',
    projectId: 'fir-entegrasyon-383cc',
    storageBucket: 'fir-entegrasyon-383cc.appspot.com',
    iosClientId: '140441317934-fm0e97ri1v60j84ddqbitagabt6rp0o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEntegrasyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh7zdIqlQRLmb5Enq8sGw_dOJorJYV4PE',
    appId: '1:140441317934:ios:e053356bf3785edcef65bf',
    messagingSenderId: '140441317934',
    projectId: 'fir-entegrasyon-383cc',
    storageBucket: 'fir-entegrasyon-383cc.appspot.com',
    iosClientId: '140441317934-fm0e97ri1v60j84ddqbitagabt6rp0o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEntegrasyon',
  );
}
